---
- name: Pull Docker Image of Calculator
  hosts: localhost
  tasks:
    - name: Pull image
      docker_image:
        name: hasan01/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name Calculator hasan01/calculator